"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MICRO_TEMPLATE_ID = exports.VUE3_TEMPLATE_ID = exports.VUE2_TEMPLATE_ID = exports.REACT_TEMPLATE_ID = exports.UMI_QIANKUN_STR = exports.REACT_STR = exports.VUE_STR = exports.MICRO_SUB_FEATURE_ID = exports.MICRO_MAIN_FEATURE_ID = exports.REACT_OPENAPI_FEATURE_ID = exports.REACT_GRAPHQL_FEATURE_ID = void 0;
exports.REACT_GRAPHQL_FEATURE_ID = 'graphql';
exports.REACT_OPENAPI_FEATURE_ID = 'openapi';
exports.MICRO_MAIN_FEATURE_ID = 'main';
exports.MICRO_SUB_FEATURE_ID = 'sub';
exports.VUE_STR = 'vue';
exports.REACT_STR = 'react';
exports.UMI_QIANKUN_STR = 'umi-qiankun';
exports.REACT_TEMPLATE_ID = 'react';
exports.VUE2_TEMPLATE_ID = 'vue2';
exports.VUE3_TEMPLATE_ID = 'vue3';
exports.MICRO_TEMPLATE_ID = 'micro';
